"""add index on hands player_id, started_at

Revision ID: a24717ca8b64
Revises: e6ada1b2e9fa
Create Date: 2026-10-06 11:57:31.079943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24717ca8b64'
down_revision: Union[str, Sequence[str], None] = 'e6ada1b2e9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_hands_player_started', 'hands', ['player_id', sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hands_player_started', table_name='hands')
    # ### end Alembic commands ###
