"""add hero_stack_start to hands

Revision ID: e6ada1b2e9fa
Revises: c573b26a6882
Create Date: 2026-09-30 17:11:30.022334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ada1b2e9fa'
down_revision: Union[str, Sequence[str], None] = 'c573b26a6882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('hero_stack_start', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'hero_stack_start')
    # ### end Alembic commands ###
