"""ORM models for the five core tables.

UUID primary keys throughout the first four, not auto-increment ints:
action_id in particular is generated by the *client* with no round-trip to
the server first (that's the whole idempotency mechanism — see
api/services/action_service.py), and a client can safely mint a random UUID
offline in a way it never could pick "the next integer."

RequestMetric is the odd one out: plain bigserial, since it has no
client-facing identity to protect — it's written server-side only, by
api/middleware/timing.py, after every /api/* response.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.db import Base


class Player(Base):
    __tablename__ = "players"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    username: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    games: Mapped[list[Game]] = relationship(back_populates="player")


class Game(Base):
    __tablename__ = "games"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    player_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("players.id"), nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="in_progress")
    # The serializer's dict (api/serializers.py) lands here whole. JSONB
    # (not plain JSON) stores it in an indexable binary form.
    current_state: Mapped[dict] = mapped_column(JSONB, nullable=False)
    # Bumped on every state write. Observability only ("this game has had 47
    # transitions") — actual write-safety next weekend comes from a row lock
    # (SELECT ... FOR UPDATE), not from comparing this number.
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    player: Mapped[Player] = relationship(back_populates="games")
    hands: Mapped[list[Hand]] = relationship(back_populates="game")


class Hand(Base):
    __tablename__ = "hands"
    __table_args__ = (
        # Covers GET /api/players/{username}/hands's exact query: filter by
        # player_id, order by started_at DESC. The DESC here is what lets
        # the planner skip a separate Sort step entirely (rows come back
        # from the index already in the right order), not just find the
        # matching rows faster. Can't write Hand.started_at.desc() here —
        # the column isn't a class attribute yet this early in the class
        # body — hence the column-name string plus a text() expression.
        Index("idx_hands_player_started", "player_id", text("started_at DESC")),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    game_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("games.id"), nullable=False)
    # Denormalized from game_id on purpose: the hand-history feature's core
    # query filters directly on player_id ("show me my hands"), and that's
    # exactly the column the index (added Weekend 4) will cover.
    player_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("players.id"), nullable=False)
    hand_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # Captured the instant this hand is dealt (hand #1: the fixed starting
    # stack; hand N+1: whatever stack carried over). Needed to compute
    # hero_net correctly once a game has more than one hand — a fixed
    # constant only worked before "next hand" existed.
    hero_stack_start: Mapped[int] = mapped_column(Integer, nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    board: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)
    hero_hole: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)
    winners: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    pot_total: Mapped[int | None] = mapped_column(Integer, nullable=True)
    hero_net: Mapped[int | None] = mapped_column(Integer, nullable=True)

    game: Mapped[Game] = relationship(back_populates="hands")
    actions: Mapped[list[Action]] = relationship(back_populates="hand")


class Action(Base):
    __tablename__ = "actions"
    __table_args__ = (
        # The idempotency guarantee lives here, at the database level, not
        # in application code: a retried request with the same action_id
        # for the same hand cannot be inserted twice, full stop.
        UniqueConstraint("hand_id", "action_id", name="uq_actions_hand_id_action_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    hand_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("hands.id"), nullable=False)
    action_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    actor_id: Mapped[str] = mapped_column(String, nullable=False)
    action_type: Mapped[str] = mapped_column(String, nullable=False)
    amount: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # The response the endpoint returned the first time. On a duplicate
    # action_id, this is replayed back instead of reapplying the action.
    response_body: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    hand: Mapped[Hand] = relationship(back_populates="actions")


class RequestMetric(Base):
    __tablename__ = "request_metrics"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    # The matched route *template* ("/api/hands/{hand_id}/actions"), not the
    # raw path with a real UUID in it — otherwise every hand/game would get
    # its own distinct "route", making aggregation across requests useless.
    route: Mapped[str] = mapped_column(String, nullable=False)
    method: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[int] = mapped_column(Integer, nullable=False)
    duration_ms: Mapped[float] = mapped_column(Numeric, nullable=False)
    observed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
